# Generated by Django 3.1.1 on 2020-09-12 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audioFiles/')),
                ('songtime_in_seconds', models.CharField(max_length=4)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('singer', models.CharField(max_length=100)),
                ('actor_actress', models.CharField(max_length=300)),
                ('movie_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BR', 'Bollywood Romance,'), ('HR', 'Hollywood Romance'), ('BRA', 'Bollywood Romance Action'), ('BR', 'Bollywood Rock'), ('BNR', 'Bollywood Nineties 90s Romance'), ('BER', 'Bollywood Eighties 80s Romance'), ('BRUP', 'Break Up Song'), ('BF', 'Best Friend'), ('FLR', 'First Love Romantic'), ('MFP', 'Mother Father Parents Family'), ('FS', 'Family Songs'), ('CH', 'Childhood Bachapan'), ('AGB', 'Anger Battle'), ('DD', 'Dance Dancing DJ Rock'), ('LRH', 'Love Romantic Romance Heart'), ('BW', 'Bollywood'), ('HW', 'HollyWood'), ('VN', 'Valentine Love'), ('RG', 'Religious'), ('AR', 'Arties Bhajan'), ('DB', 'Patriotism Desh Bhakti DeshBhakti'), ('RAL', 'Revenge Anger Love')], max_length=5)),
                ('language', models.CharField(choices=[('HN', 'Hindi'), ('EN', 'English'), ('PB', 'Punjabi'), ('TM', 'Tamil'), ('TL', 'Telugu'), ('MH', 'Marathi'), ('GJ', 'Gujrati'), ('BJ', 'Bhoojpuri'), ('HR', 'Haryanvi'), ('RJ', 'Rajasthani')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SongLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('playlist_logo', models.FileField(upload_to='images/')),
                ('songs', models.ManyToManyField(to='core.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
