# Generated by Django 3.1.1 on 2020-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
