# Generated by Django 3.1.1 on 2020-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
