# Generated by Django 3.1.1 on 2020-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title', 'publish_date')},
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audioFile1s/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('BR', 'Bollywood Romance,'), ('HR', 'Hollywood Romance'), ('BRA', 'Bollywood Romance Action'), ('BR', 'Bollywood Rock'), ('BNR', 'Bollywood Nineties 90s Romance'), ('BER', 'Bollywood Eighties 80s Romance'), ('BRUP', 'Break Up Song'), ('BF', 'Best Friend'), ('FLR', 'First Love Romantic'), ('MFP', 'Mother Father Parents Family'), ('FS', 'Family Songs'), ('CH', 'Childhood Bachapan'), ('AGB', 'Anger Battle'), ('DD', 'Dance Dancing DJ Rock'), ('LRH', 'Love Romantic Romance Heart'), ('BW', 'Bollywood'), ('HW', 'HollyWood'), ('VN', 'Valentine Love'), ('RG', 'Religious'), ('AR', 'Arties Bhajan'), ('DB', 'Patriotism Desh Bhakti DeshBhakti'), ('RAL', 'Revenge Anger Love'), ('RM', 'Romance'), ('LV', 'Love')], max_length=5),
        ),
    ]
