# Generated by Django 3.1.1 on 2020-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200918_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audioFile1s/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
