# Generated by Django 3.1.1 on 2020-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200918_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_logo',
            field=models.FileField(upload_to='images/playlist_logo/'),
        ),
    ]
